config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#facebook_login'

  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'


  resources :activations 
  resources :carriers
  resources :phones do
    resources :activations, shallow: true
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activation.rb
class Activation < ApplicationRecord
  belongs_to :user
  belongs_to :carrier
  belongs_to :phone

  validates :phone_number, :IMEI, presence: true
  validates :IMEI, :phone_number, uniqueness: true
  validates :phone_number, length: {is: 10}
  validates :IMEI, length: {is: 15}


  def self.by_user(user_id)
    where(user: user_id)
  end

  def self.with_carrier(carrier_id)
    where(carrier: carrier_id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carrier.rb
class Carrier < ApplicationRecord
    has_many :activations
    has_many :phones, through: :activations

    validates :name, presence: true

end

app/models/phone.rb
class Phone < ApplicationRecord
    has_many :activations
    has_many :carriers, through: :activations

    validates :manufacturer, :model,  :storage, presence: true
   
end

app/models/user.rb
class User < ApplicationRecord
    has_many :activations, dependent: :destroy
    has_secure_password

    validates :username, :email, presence: true
    validates :email, :username, uniqueness: true
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index]

    def index
        @users = User.all
        @carriers = Carrier.all

        if !params[:user].blank? && !params[:carrier].blank?
            @activations = Activation.by_user(params[:user]).with_carrier(params[:carrier])
        elsif !params[:user].blank?
            @activations = Activation.by_user(params[:user])
        elsif !params[:carrier].blank?
            @activations = Activation.with_carrier(params[:carrier])
        else
            @activations = Activation.all
        end
    end

    def show
        @activation = Activation.find_by_id(params[:id])
        if !@activation
            flash[:message]= "Activation you are looking for does not exits!!" 
            redirect_to '/' 
        end
    end

    def new
        if params[:phone_id] && @phone = Phone.find_by_id(params[:phone_id])
            @activation = @phone.activations.new
        else
            @activation =Activation.new
        end
    end

    def create
        @activation = Activation.new(activation_params)
        if @activation.save
            redirect_to activations_path(@activation)
        else
            render :new
        end
    end

    def activation_params
        params.require(:activation).permit(:phone_number, :IMEI, :phone_id, :carrier_id, :user_id)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_login

    private
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
       redirect_to '/' if !logged_in?
    end

    def require_login
        if !logged_in?
            flash[:message] = "You need to Log In to view this page" 
            redirect_to '/' 
        end
    end
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index]

    def new
        @carrier = Carrier.new
    end
    
    def create
        @carrier = Carrier.new(carrier_params)
        if @carrier.save
            redirect_to carriers_path
        else
            render :new
        end
    end

    def index
        @carriers = Carrier.all
    end

    def carrier_params
        params.require(:carrier).permit(:name, :cost, :rating )
    end

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index]

    def new
        @phone = Phone.new
    end

    def show
        @phone = Phone.find_by_id(params[:id])
        if !@phone
            flash[:message]= "The Phone you are looking for does not exits!!" 
            redirect_to '/' 
        end
    end
    def index
        @phones = Phone.all
    end
    
    def create
        @phone = Phone.new(phone_params)
        if @phone.save
            redirect_to phones_path
        else
            render :new
        end
    end

    def phone_params
        params.require(:phone).permit(:model, :manufacturer, :storage )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def home
    end

    def destroy
        session.clear
        redirect_to root_path
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = "Incorrect login info, please try again!!"
            redirect_to "/login"
        end

    end

    def facebook_login
        @user = User.find_or_create_by(email: auth["info"]["email"])do |user|
            user.username= auth["info"]["name"]
            user.password= SecureRandom.hex(10)

        end
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to '/'
        end
        
    end

    def auth
        request.env['omniauth.auth']
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def edit
        @user = User.find_by_id(params[:id])
        if session[:user_id] == @user.id
            render :edit
        else
            flash[:message]= "You do not have permission to make this change"
            redirect_to '/'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        if !@user
            flash[:message]= "User you are looking for does not exits!!" 
            redirect_to '/' 
        end
    end

    def destroy
        @user = User.find_by_id(params[:id])
        if session[:user_id] == @user.id
            @user.destroy
            redirect_to '/logout'
        else
            flash[:message]= "You do not have permission to make this change"
            redirect_to '/'
        end
        
    end

    def update
        user = User.find_by_id(params[:id])
        user.update(user_params)
        user.save
        binding.pry
        redirect_to user_path(user)
    end

    private

    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end
end

app/helpers/activations_helper.rb
module ActivationsHelper
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activations/index.html.erb
<div class ="header"> All Activations </div>

<p>Filter activations: 
<%= form_tag("/activations", method: "get") do %>
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "name"), include_blank: true%>
    <%= select_tag "carrier", options_from_collection_for_select(@carriers, "id", "name"), include_blank: true%>
    <%= submit_tag "Filter" %>
  <% end %>
</p>

<ul>
    <% @activations.each do |activation| %>
        <div class= "main-content">
        Phone Number:  <%= activation.phone_number %>  
       
        Activated By: <%= activation.user.name %> 

        <%= link_to 'Details about this activation', activation_path(activation.id) %><br>
       </div>
       <br>

    <% end %>
</ul>

app/views/activations/new.html.erb
<div class ="header"> Add a New Activation </div>

<%= render partial: "layouts/errors", locals: {object: @activation} %>

<%= form_for(@activation) do |f| %>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
    <br>
    <%= f.label :IMEI %>
    <%= f.text_field :IMEI %>
    <br>
    <%= f.label :phone_id %>
    <%= f.collection_select :phone_id, Phone.all , :id, :model %>
    <br>
    <%= f.label :carrier_id %>
    <%= f.collection_select :carrier_id, Carrier.all , :id, :name %>
    <br>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.submit %>

<% end %>

app/views/activations/show.html.erb
<div class="header"> Details about the activation </div>
<div class ="main-content">
Phone Number: <%= @activation.phone_number %><br>
IMEI: <%= @activation.IMEI %><br>
Activated Device: <%=@activation.phone.model %><br>
Storage: <%= @activation.phone.storage %><br>
Carrier: <%=@activation.carrier.name %>
</div>

app/views/carriers/index.html.erb
<div class ="header"> All Carrier </div>
<ul>
    <div class ="main-content">
    <% @carriers.each do |carrier| %>
        Name:  <%= carrier.name %>  <br>
        Cost: <%= carrier.cost %>  <br>
        Rating(Out of 5): <%= carrier.rating %> <br><br>
    <% end %>
    </div>
</ul>

app/views/carriers/new.html.erb
<div class ="header">  New Carrier </div>

<%= render partial: "layouts/errors", locals: {object: @carrier} %>

<%= form_for(@carrier) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <br>
    <%= f.label :rating %>
    <%= f.text_field :rating %>

    <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="error_explanation">
  <%= pluralize(object.errors.count, "error") %> prohibited this from being saved:

  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivationTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav-bar">
      <% if logged_in? %>
        <div class="log-out">
          <%=link_to "Log Out", logout_path, method:"delete" %>
        </div>
        <div class="nav-buttons">
          <%=link_to "Add a Phone", new_phone_path %> |
          <%=link_to "All Phones", phones_path %> |
          <%=link_to "Add a Carrier", new_carrier_path %> |
          <%=link_to "All Carriers", carriers_path %>|
          <%=link_to "All Activation", activations_path %>
        </div>
      <% else %>
        <div class="log-in">
          <%=link_to "Sign Up", signup_path %> |
          <%=link_to "Log In", login_path %> 
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/phones/_phone.html.erb
<div class ="main-content">
<%= phone.model %>  - <%= phone.manufacturer %> - <%= phone.storage %> 

<%= link_to 'Activate this phone', new_phone_activation_path(phone.id) %>
</div>

app/views/phones/index.html.erb
<div class ="header"> All Phones </div>

<ul>
    <% @phones.each do |p| %>
        <%= render partial: "phone", locals:{phone: p} %>
    <% end %>
</ul>

app/views/phones/new.html.erb
<div class ="header"> New Phone ! </div>

<%= render partial: "layouts/errors", locals: {object: @phone} %>

<%= form_for(@phone) do |f| %>
    <%= f.label :model %>
    <%= f.text_field :model %>
    <br>
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
    <br>
    <%= f.label :storage %>
    <%= f.text_field :storage %>

    <%= f.submit %>
<% end %>

app/views/phones/show.html.erb
<div class ="header"> Details about Phone ! </div>
<%= render partial: "phone", locals:{phone: @phone} %>

app/views/users/_user.html.erb
<%= form_with model: user, local:true do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
    <br>
    <%= f.label :username %>:
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %>:
    <%= f.email_field :email %>
    <br>
    <% if ! user.id %>
        <%= f.label :password %>:
        <%= f.password_field :password %>
    <% end %>

    <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<%= render "user", user: @user %>

app/views/users/new.html.erb
<div class ="header"> Sign Up! </div> 
<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= render "user", user: @user %>

app/views/users/show.html.erb
<div class ="header"> Welcome <%= @user.username %><br>
User Info: </div>

<div class ="main-content">
    Name:<%= @user.name %><br>
    Email:<%= @user.email %><br>
    Username:<%= @user.username %><br>
    <%=link_to "Edit", edit_user_path(@user) %>
    <%=button_to "Delete", @user, method: :delete%>
</div>